# Example: Basic Homebrew Update Workflow
#
# This workflow automatically updates your Homebrew formula when you push changes
# to the main branch. Copy this file to .github/workflows/ in your source repository.

name: Update Homebrew Formula

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'bin/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    name: Update Homebrew Tap

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for version generation

      - name: Update Homebrew formula
        uses: cajias/custom-github-actions/homebrew-update@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tap_repo_token: ${{ secrets.TAP_REPO_TOKEN }}
          github_user: your-username
          source_repo: your-project
          tap_repo: homebrew-tools
          formula_name: your-formula
          formula_path: Formula/your-formula.rb
          version_strategy: date-commit

      - name: Display results
        run: |
          echo "Formula updated successfully!"
          echo "Version: ${{ steps.update.outputs.version }}"
          echo "Release: ${{ steps.update.outputs.release_url }}"
