# Example: Semver-based Homebrew Update Workflow
#
# This workflow uses semantic versioning to automatically increment the patch version.
# Copy this file to .github/workflows/ in your source repository.

name: Update Homebrew Formula (Semver)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    name: Update Homebrew Tap with Semver

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important: Required for semver strategy

      - name: Update Homebrew formula
        id: update
        uses: cajias/custom-github-actions/homebrew-update@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tap_repo_token: ${{ secrets.TAP_REPO_TOKEN }}
          github_user: your-username
          source_repo: your-project
          tap_repo: homebrew-tools
          formula_name: your-formula
          formula_path: Formula/your-formula.rb
          version_strategy: semver

      - name: Display results
        run: |
          echo "✅ Formula updated successfully!"
          echo "📦 Version: ${{ steps.update.outputs.version }}"
          echo "🏷️  Tag: ${{ steps.update.outputs.tag }}"
          echo "🔗 Release: ${{ steps.update.outputs.release_url }}"
